In [1]:
import pandas as pd

group_fixtures = pd.read_csv('datacamp_data_group_fixtures.csv')
group_fixtures

,index,match_id,group,home_team,away_team,date_utc,venue
0,0,1,A,Mexico,South Africa,2026-06-11T19:00:00Z,"Estadio Azteca, Mexico City"
1,1,2,A,South Korea,UEFA Playoff D,2026-06-12T02:00:00Z,"Estadio Akron, Guadalajara"
2,2,3,B,Canada,UEFA Playoff A,2026-06-12T19:00:00Z,"BMO Field, Toronto"
3,3,4,D,USA,Paraguay,2026-06-13T01:00:00Z,"SoFi Stadium, Los Angeles"
4,4,5,D,Australia,UEFA Playoff C,2026-06-13T04:00:00Z,"BC Place, Vancouver"
...,...,...,...,...,...,...,...
67,67,68,L,Croatia,Ghana,2026-06-27T21:00:00Z,"Lincoln Financial Field, Philadelphia"
68,68,69,K,Colombia,Portugal,2026-06-27T23:30:00Z,"Hard Rock Stadium, Miami"
69,69,70,K,FIFA Playoff 1,Uzbekistan,2026-06-27T23:30:00Z,"Mercedes-Benz Stadium, Atlanta"
70,70,71,J,Algeria,Austria,2026-06-28T02:00:00Z,"GEHA Field at Arrowhead Stadium, Kansas City"
71,71,72,J,Jordan,Argentina,2026-06-28T02:00:00Z,"AT&T Stadium, Dallas"

In [2]:
knockout_slots = pd.read_csv('datacamp_data_knockout_slots.csv')
knockout_slots

,index,match_id,round,multiplier,date_utc,venue,slot_home,slot_away
0,0,73,Round of 32,1,2026-06-28T19:00:00Z,"SoFi Stadium, Los Angeles",Runner-up Group A,Runner-up Group B
1,1,74,Round of 32,1,2026-06-29T17:00:00Z,"NRG Stadium, Houston",Winner Group C,Runner-up Group F
2,2,75,Round of 32,1,2026-06-29T20:30:00Z,"Gillette Stadium, Boston",Winner Group E,Best 3rd (Groups A/B/C/D/F)
3,3,76,Round of 32,1,2026-06-30T01:00:00Z,"Estadio BBVA, Monterrey",Winner Group F,Runner-up Group C
4,4,77,Round of 32,1,2026-06-30T17:00:00Z,"AT&T Stadium, Dallas",Runner-up Group E,Runner-up Group I
5,5,78,Round of 32,1,2026-06-30T21:00:00Z,"MetLife Stadium, East Rutherford",Winner Group I,Best 3rd (Groups C/D/F/G/H)
6,6,79,Round of 32,1,2026-07-01T01:00:00Z,"Estadio Azteca, Mexico City",Winner Group A,Best 3rd (Groups C/E/F/H/I)
7,7,80,Round of 32,1,2026-07-01T16:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Group L,Best 3rd (Groups E/H/I/J/K)
8,8,81,Round of 32,1,2026-07-01T20:00:00Z,"Lumen Field, Seattle",Winner Group G,Best 3rd (Groups A/E/H/I/J)
9,9,82,Round of 32,1,2026-07-02T00:00:00Z,"Levi's Stadium, Santa Clara",Winner Group D,Best 3rd (Groups B/E/F/I/J)
10,10,83,Round of 32,1,2026-07-02T19:00:00Z,"BMO Field, Toronto",Runner-up Group K,Runner-up Group L
11,11,84,Round of 32,1,2026-07-02T23:00:00Z,"SoFi Stadium, Los Angeles",Winner Group H,Runner-up Group J
12,12,85,Round of 32,1,2026-07-03T03:00:00Z,"BC Place, Vancouver",Winner Group B,Best 3rd (Groups E/F/G/I/J)
13,13,86,Round of 32,1,2026-07-03T18:00:00Z,"AT&T Stadium, Dallas",Runner-up Group D,Runner-up Group G
14,14,87,Round of 32,1,2026-07-03T22:00:00Z,"Hard Rock Stadium, Miami",Winner Group J,Runner-up Group H
15,15,88,Round of 32,1,2026-07-04T01:30:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",Winner Group K,Best 3rd (Groups D/E/I/J/L)
16,16,89,Round of 16,2,2026-07-04T17:00:00Z,"NRG Stadium, Houston",Winner Match 73,Winner Match 75
17,17,90,Round of 16,2,2026-07-04T21:00:00Z,"Lincoln Financial Field, Philadelphia",Winner Match 74,Winner Match 77
18,18,91,Round of 16,2,2026-07-05T20:00:00Z,"MetLife Stadium, East Rutherford",Winner Match 76,Winner Match 78
19,19,92,Round of 16,2,2026-07-06T00:00:00Z,"Estadio Azteca, Mexico City",Winner Match 79,Winner Match 80
20,20,93,Round of 16,2,2026-07-06T19:00:00Z,"AT&T Stadium, Dallas",Winner Match 83,Winner Match 84
21,21,94,Round of 16,2,2026-07-07T00:00:00Z,"Lumen Field, Seattle",Winner Match 81,Winner Match 82
22,22,95,Round of 16,2,2026-07-07T16:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Match 86,Winner Match 88
23,23,96,Round of 16,2,2026-07-07T20:00:00Z,"BC Place, Vancouver",Winner Match 85,Winner Match 87
24,24,97,Quarter-final,4,2026-07-09T20:00:00Z,"Gillette Stadium, Boston",Winner Match 89,Winner Match 90
25,25,98,Quarter-final,4,2026-07-10T19:00:00Z,"SoFi Stadium, Los Angeles",Winner Match 93,Winner Match 94
26,26,99,Quarter-final,4,2026-07-11T21:00:00Z,"Hard Rock Stadium, Miami",Winner Match 91,Winner Match 92
27,27,100,Quarter-final,4,2026-07-12T01:00:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",Winner Match 95,Winner Match 96
28,28,101,Semi-final,8,2026-07-14T19:00:00Z,"AT&T Stadium, Dallas",Winner Match 97,Winner Match 98
29,29,102,Semi-final,8,2026-07-15T19:00:00Z,"Mercedes-Benz Stadium, Atlanta",Winner Match 99,Winner Match 100
30,30,103,Third-place playoff,8,2026-07-18T21:00:00Z,"Hard Rock Stadium, Miami",Loser Match 101,Loser Match 102
31,31,104,Final,16,2026-07-19T19:00:00Z,"MetLife Stadium, East Rutherford",Winner Match 101,Winner Match 102

In [3]:
group_predictions = group_fixtures.copy()

import math

METRICS = {
    'Mexico': {'att': 0.403681, 'def': 0.531698},
    'South Africa': {'att': 0.284534, 'def': 0.254915},
    'South Korea': {'att': 0.635600, 'def': 0.407639},
    'UEFA Playoff D': {'att': 0.363210, 'def': 0.129745},
    'Canada': {'att': 0.436639, 'def': 0.458146},
    'UEFA Playoff A': {'att': 0.490785, 'def': 0.274114},
    'USA': {'att': 0.536008, 'def': 0.291174},
    'Paraguay': {'att': 0.129019, 'def': 0.428593},
    'Australia': {'att': 0.563374, 'def': 0.564131},
    'UEFA Playoff C': {'att': 0.168900, 'def': 0.202706},
    'Qatar': {'att': 0.332429, 'def': -0.088076},
    'Switzerland': {'att': 0.574638, 'def': 0.345232},
    'Brazil': {'att': 0.647404, 'def': 0.503534},
    'Morocco': {'att': 0.666100, 'def': 0.598162},
    'Haiti': {'att': 0.531534, 'def': 0.084438},
    'Scotland': {'att': 0.357567, 'def': 0.219828},
    'Germany': {'att': 0.778768, 'def': 0.340253},
    'Curaçao': {'att': 0.334359, 'def': 0.217154},
    'Netherlands': {'att': 0.721324, 'def': 0.368518},
    'Japan': {'att': 0.822866, 'def': 0.597894},
    "Côte d'Ivoire": {'att': 0.383208, 'def': 0.498407},
    'Ecuador': {'att': 0.119807, 'def': 0.729039},
    'UEFA Playoff B': {'att': 0.408480, 'def': 0.003005},
    'Tunisia': {'att': 0.286335, 'def': 0.572097},
    'Spain': {'att': 0.897226, 'def': 0.570835},
    'Cabo Verde': {'att': 0.189980, 'def': 0.204487},
    'Belgium': {'att': 0.556586, 'def': 0.370366},
    'Egypt': {'att': 0.301451, 'def': 0.538440},
    'Saudi Arabia': {'att': 0.153911, 'def': 0.416954},
    'Uruguay': {'att': 0.324385, 'def': 0.613394},
    'Iran': {'att': 0.577427, 'def': 0.412291},
    'New Zealand': {'att': 0.671585, 'def': 0.355134},
    'Austria': {'att': 0.456821, 'def': 0.335934},
    'Jordan': {'att': 0.553099, 'def': 0.258547},
    'France': {'att': 0.703797, 'def': 0.550004},
    'FIFA Playoff 2': {'att': 0.101994, 'def': -0.119005},
    'Norway': {'att': 0.759002, 'def': 0.295479},
    'Senegal': {'att': 0.593584, 'def': 0.517812},
    'Algeria': {'att': 0.624009, 'def': 0.398613},
    'Argentina': {'att': 0.719640, 'def': 0.640277},
    'Portugal': {'att': 0.778109, 'def': 0.457732},
    'FIFA Playoff 1': {'att': 0.208404, 'def': 0.583596},
    'Uzbekistan': {'att': 0.332026, 'def': 0.479396},
    'Colombia': {'att': 0.637680, 'def': 0.467223},
    'England': {'att': 0.724087, 'def': 0.632964},
    'Croatia': {'att': 0.527677, 'def': 0.442115},
    'Ghana': {'att': 0.249478, 'def': 0.243327},
    'Panama': {'att': 0.464179, 'def': 0.218279},
}

RHO = -0.03
MAX_GOALS = 8

def lambdas(home, away):
    h, a = METRICS[home], METRICS[away]
    return math.exp(h['att'] - a['def']), math.exp(a['att'] - h['def'])

def tau(h, a, lh, la):
    if h == 0 and a == 0:
        return 1.0 - lh * la * RHO
    if h == 0 and a == 1:
        return 1.0 + lh * RHO
    if h == 1 and a == 0:
        return 1.0 + la * RHO
    if h == 1 and a == 1:
        return 1.0 - RHO
    return 1.0

def pois_pmf(k, lam):
    return math.exp(k * math.log(lam) - lam - math.lgamma(k + 1))

def most_likely_score(home, away):
    lh, la = lambdas(home, away)
    best_h, best_a, best_p = 0, 0, -1.0
    for h in range(MAX_GOALS + 1):
        for a in range(MAX_GOALS + 1):
            p = tau(h, a, lh, la) * pois_pmf(h, lh) * pois_pmf(a, la)
            if p > best_p:
                best_h, best_a, best_p = h, a, p
    return best_h, best_a

def winning_team_label(h, a):
    if h > a:
        return 'home'
    if h < a:
        return 'away'
    return 'draw'

def baseline_cards_corners(home, away):
    ha = METRICS[home]['att']
    aa = METRICS[away]['att']
    corners = max(4, int(round(8 + (ha + aa) * 1.5)))
    yellows = max(1, int(round(2 + (ha + aa) * 0.8)))
    return corners, yellows, 0

pred_h, pred_a, winners, corners, yellows, reds = [], [], [], [], [], []

for _, row in group_predictions.iterrows():
    home = row['home_team']
    away = row['away_team']
    if home not in METRICS:
        raise KeyError(f"Missing METRICS key for home team: {home!r}")
    if away not in METRICS:
        raise KeyError(f"Missing METRICS key for away team: {away!r}")
    h, a = most_likely_score(home, away)
    c, y, r = baseline_cards_corners(home, away)
    pred_h.append(h)
    pred_a.append(a)
    winners.append(winning_team_label(h, a))
    corners.append(c)
    yellows.append(y)
    reds.append(r)

group_predictions['predicted_home_goals'] = pred_h
group_predictions['predicted_away_goals'] = pred_a
group_predictions['corners'] = corners
group_predictions['yellow_cards'] = yellows
group_predictions['red_cards'] = reds
group_predictions['winning_team'] = winners

group_predictions

# 1. Output the table directly on your screen inside JupyterLab
import pandas as pd
display(group_predictions)

# 2. Save the data pipeline calculations into your designated CSV file
group_predictions.to_csv('Output_Datacamp_Group_Stage_2026-06-11.csv', index=False)

,index,match_id,group,home_team,away_team,date_utc,venue,predicted_home_goals,predicted_away_goals,corners,yellow_cards,red_cards,winning_team
0,0,1,A,Mexico,South Africa,2026-06-11T19:00:00Z,"Estadio Azteca, Mexico City",1,0,9,3,0,home
1,1,2,A,South Korea,UEFA Playoff D,2026-06-12T02:00:00Z,"Estadio Akron, Guadalajara",1,1,9,3,0,draw
2,2,3,B,Canada,UEFA Playoff A,2026-06-12T19:00:00Z,"BMO Field, Toronto",1,1,9,3,0,draw
3,3,4,D,USA,Paraguay,2026-06-13T01:00:00Z,"SoFi Stadium, Los Angeles",1,0,9,3,0,home
4,4,5,D,Australia,UEFA Playoff C,2026-06-13T04:00:00Z,"BC Place, Vancouver",1,0,9,3,0,home
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,67,68,L,Croatia,Ghana,2026-06-27T21:00:00Z,"Lincoln Financial Field, Philadelphia",1,0,9,3,0,home
68,68,69,K,Colombia,Portugal,2026-06-27T23:30:00Z,"Hard Rock Stadium, Miami",1,1,10,3,0,draw
69,69,70,K,FIFA Playoff 1,Uzbekistan,2026-06-27T23:30:00Z,"Mercedes-Benz Stadium, Atlanta",0,0,9,2,0,draw
70,70,71,J,Algeria,Austria,2026-06-28T02:00:00Z,"GEHA Field at Arrowhead Stadium, Kansas City",1,1,10,3,0,draw
71,71,72,J,Jordan,Argentina,2026-06-28T02:00:00Z,"AT&T Stadium, Dallas",0,1,10,3,0,away

In [ ]:
knockout_predictions = knockout_slots.copy()

import math
import re

# Map DataCamp display names -> ASCII keys (avoids paste/encoding issues)
TEAM_TO_METRIC = {
    "Côte d'Ivoire": "Cote d Ivoire",
    "Curaçao": "Curacao",
}

# Group cell already loaded METRICS with accented keys — add aliases:
if 'METRICS' in globals():
    METRICS['Curacao'] = METRICS['Curaçao']
    METRICS['Cote d Ivoire'] = METRICS["Côte d'Ivoire"]

def metric_name(team):
    return TEAM_TO_METRIC.get(team, team)

if 'METRICS' not in globals():
    METRICS = {
        'Mexico': {'att': 0.403681, 'def': 0.531698},
        'South Africa': {'att': 0.284534, 'def': 0.254915},
        'South Korea': {'att': 0.635600, 'def': 0.407639},
        'UEFA Playoff D': {'att': 0.363210, 'def': 0.129745},
        'Canada': {'att': 0.436639, 'def': 0.458146},
        'UEFA Playoff A': {'att': 0.490785, 'def': 0.274114},
        'USA': {'att': 0.536008, 'def': 0.291174},
        'Paraguay': {'att': 0.129019, 'def': 0.428593},
        'Australia': {'att': 0.563374, 'def': 0.564131},
        'UEFA Playoff C': {'att': 0.168900, 'def': 0.202706},
        'Qatar': {'att': 0.332429, 'def': -0.088076},
        'Switzerland': {'att': 0.574638, 'def': 0.345232},
        'Brazil': {'att': 0.647404, 'def': 0.503534},
        'Morocco': {'att': 0.666100, 'def': 0.598162},
        'Haiti': {'att': 0.531534, 'def': 0.084438},
        'Scotland': {'att': 0.357567, 'def': 0.219828},
        'Germany': {'att': 0.778768, 'def': 0.340253},
        'Curacao': {'att': 0.334359, 'def': 0.217154},
        'Netherlands': {'att': 0.721324, 'def': 0.368518},
        'Japan': {'att': 0.822866, 'def': 0.597894},
        'Cote d Ivoire': {'att': 0.383208, 'def': 0.498407},
        'Ecuador': {'att': 0.119807, 'def': 0.729039},
        'UEFA Playoff B': {'att': 0.408480, 'def': 0.003005},
        'Tunisia': {'att': 0.286335, 'def': 0.572097},
        'Spain': {'att': 0.897226, 'def': 0.570835},
        'Cabo Verde': {'att': 0.189980, 'def': 0.204487},
        'Belgium': {'att': 0.556586, 'def': 0.370366},
        'Egypt': {'att': 0.301451, 'def': 0.538440},
        'Saudi Arabia': {'att': 0.153911, 'def': 0.416954},
        'Uruguay': {'att': 0.324385, 'def': 0.613394},
        'Iran': {'att': 0.577427, 'def': 0.412291},
        'New Zealand': {'att': 0.671585, 'def': 0.355134},
        'Austria': {'att': 0.456821, 'def': 0.335934},
        'Jordan': {'att': 0.553099, 'def': 0.258547},
        'France': {'att': 0.703797, 'def': 0.550004},
        'FIFA Playoff 2': {'att': 0.101994, 'def': -0.119005},
        'Norway': {'att': 0.759002, 'def': 0.295479},
        'Senegal': {'att': 0.593584, 'def': 0.517812},
        'Algeria': {'att': 0.624009, 'def': 0.398613},
        'Argentina': {'att': 0.719640, 'def': 0.640277},
        'Portugal': {'att': 0.778109, 'def': 0.457732},
        'FIFA Playoff 1': {'att': 0.208404, 'def': 0.583596},
        'Uzbekistan': {'att': 0.332026, 'def': 0.479396},
        'Colombia': {'att': 0.637680, 'def': 0.467223},
        'England': {'att': 0.724087, 'def': 0.632964},
        'Croatia': {'att': 0.527677, 'def': 0.442115},
        'Ghana': {'att': 0.249478, 'def': 0.243327},
        'Panama': {'att': 0.464179, 'def': 0.218279},
    }
    RHO = -0.03
    MAX_GOALS = 8

    def m(team):
        return METRICS[metric_name(team)]

    def lambdas(home, away):
        h, a = m(home), m(away)
        return math.exp(h['att'] - a['def']), math.exp(a['att'] - h['def'])

    def tau(h, a, lh, la):
        if h == 0 and a == 0:
            return 1.0 - lh * la * RHO
        if h == 0 and a == 1:
            return 1.0 + lh * RHO
        if h == 1 and a == 0:
            return 1.0 + la * RHO
        if h == 1 and a == 1:
            return 1.0 - RHO
        return 1.0

    def pois_pmf(k, lam):
        return math.exp(k * math.log(lam) - lam - math.lgamma(k + 1))

    def most_likely_score(home, away):
        lh, la = lambdas(home, away)
        best_h, best_a, best_p = 0, 0, -1.0
        for h in range(MAX_GOALS + 1):
            for a in range(MAX_GOALS + 1):
                p = tau(h, a, lh, la) * pois_pmf(h, lh) * pois_pmf(a, la)
                if p > best_p:
                    best_h, best_a, best_p = h, a, p
        return best_h, best_a

    def baseline_cards_corners(home, away):
        ha, aa = m(home)['att'], m(away)['att']
        corners = max(4, int(round(8 + (ha + aa) * 1.5)))
        yellows = max(1, int(round(2 + (ha + aa) * 0.8)))
        return corners, yellows, 0
else:
    def m(team):
        return METRICS[metric_name(team)]

# --- Group standings from group_predictions ---
def init_standings(fixtures):
    tables = {}
    for grp in sorted(fixtures['group'].unique()):
        teams = pd.unique(
            fixtures.loc[fixtures['group'] == grp, ['home_team', 'away_team']].values.ravel()
        )
        tables[grp] = {t: {'pts': 0, 'gf': 0, 'ga': 0} for t in teams}
    return tables

def apply_match(tables, grp, home, away, hg, ag):
    tables[grp][home]['gf'] += hg
    tables[grp][home]['ga'] += ag
    tables[grp][away]['gf'] += ag
    tables[grp][away]['ga'] += hg
    if hg > ag:
        tables[grp][home]['pts'] += 3
    elif ag > hg:
        tables[grp][away]['pts'] += 3
    else:
        tables[grp][home]['pts'] += 1
        tables[grp][away]['pts'] += 1

def rank_group(tables, grp):
    return sorted(
        tables[grp].keys(),
        key=lambda t: (
            -tables[grp][t]['pts'],
            -(tables[grp][t]['gf'] - tables[grp][t]['ga']),
            -tables[grp][t]['gf'],
            t,
        ),
    )

standings = init_standings(group_fixtures)
for _, row in group_predictions.iterrows():
    apply_match(
        standings,
        row['group'],
        row['home_team'],
        row['away_team'],
        int(row['predicted_home_goals']),
        int(row['predicted_away_goals']),
    )

third_team = {g: rank_group(standings, g)[2] for g in standings}
third_rank = sorted(
    third_team.keys(),
    key=lambda g: (
        -standings[g][third_team[g]]['pts'],
        -(standings[g][third_team[g]]['gf'] - standings[g][third_team[g]]['ga']),
        -(standings[g][third_team[g]]['gf']),
    ),
)
qualified_third_groups = set(third_rank[:8])
third_assignments = {}

def parse_best_third_groups(slot):
    m = re.search(r'Groups (.+)\)', slot)
    return m.group(1).replace(' ', '').split('/') if m else []

def preassign_best_thirds():
    global third_assignments
    third_assignments = {}

    slots = []
    seen = set()
    for _, row in knockout_predictions.sort_values('match_id').iterrows():
        for col in ['slot_home', 'slot_away']:
            s = str(row[col])
            if s.startswith('Best 3rd') and s not in seen:
                seen.add(s)
                slots.append(s)

    def backtrack(i, used_teams):
        if i >= len(slots):
            return True
        slot = slots[i]
        pools = parse_best_third_groups(slot)
        for g in third_rank:
            if g not in qualified_third_groups or g not in pools:
                continue
            team = third_team[g]
            if team in used_teams:
                continue
            third_assignments[slot] = team
            if backtrack(i + 1, used_teams | {team}):
                return True
            del third_assignments[slot]
        return False

    if not backtrack(0, set()):
        used = set()
        for slot in slots:
            pools = parse_best_third_groups(slot)
            team = None
            for g in third_rank:
                if g in pools and g in qualified_third_groups:
                    t = third_team[g]
                    if t not in used:
                        team = t
                        break
            if team is None:
                for g in third_rank:
                    if g in pools:
                        t = third_team[g]
                        if t not in used:
                            team = t
                            break
            if team is None:
                raise ValueError('Cannot assign third-place team for: ' + slot)
            third_assignments[slot] = team
            used.add(team)

def pick_best_third(slot):
    return third_assignments[slot]

def resolve_slot(slot, match_winners, match_losers):
    slot = str(slot).strip()
    if slot.startswith('Winner Group '):
        return rank_group(standings, slot.replace('Winner Group ', ''))[0]
    if slot.startswith('Runner-up Group '):
        return rank_group(standings, slot.replace('Runner-up Group ', ''))[1]
    if slot.startswith('Best 3rd'):
        return pick_best_third(slot)
    if slot.startswith('Winner Match '):
        return match_winners[int(slot.replace('Winner Match ', ''))]
    if slot.startswith('Loser Match '):
        return match_losers[int(slot.replace('Loser Match ', ''))]
    return slot

def knockout_winner(home, away, hg, ag):
    if hg != ag:
        return ('home' if hg > ag else 'away'), False
    lh, la = lambdas(home, away)
    return ('home' if lh >= la else 'away'), True

preassign_best_thirds()

match_winners, match_losers = {}, {}
pred_home_teams, pred_away_teams = [], []
pred_h, pred_a, winners, pens = [], [], [], []
corners, yellows, reds = [], [], []

for _, row in knockout_predictions.sort_values('match_id').iterrows():
    mid = int(row['match_id'])
    home = resolve_slot(row['slot_home'], match_winners, match_losers)
    away = resolve_slot(row['slot_away'], match_winners, match_losers)

    hg, ag = most_likely_score(home, away)
    winner_side, penalties = knockout_winner(home, away, hg, ag)
    c, y, r = baseline_cards_corners(home, away)

    pred_home_teams.append(home)
    pred_away_teams.append(away)
    pred_h.append(hg)
    pred_a.append(ag)
    winners.append(winner_side)
    pens.append(bool(penalties))
    corners.append(c)
    yellows.append(y)
    reds.append(r)

    if winner_side == 'home':
        match_winners[mid] = home
        match_losers[mid] = away
    else:
        match_winners[mid] = away
        match_losers[mid] = home

knockout_predictions['predicted_home_team'] = pred_home_teams
knockout_predictions['predicted_away_team'] = pred_away_teams
knockout_predictions['predicted_home_goals'] = pred_h
knockout_predictions['predicted_away_goals'] = pred_a
knockout_predictions['corners'] = corners
knockout_predictions['yellow_cards'] = yellows
knockout_predictions['red_cards'] = reds
knockout_predictions['match_winner'] = winners
knockout_predictions['penalties'] = pens

knockout_predictions

# 1. Output the table directly on your screen inside JupyterLab
import pandas as pd
display(knockout_predictions)

# 2. Save the data pipeline calculations into your designated CSV file
knockout_predictions.to_csv('Output_Datacamp_Knockout_Stage_2026-06-11.csv', index=False)